### PR TITLE
opae-lib: remove MCP metrics support

### PR DESCRIPTION
**Pull request by anandaravuri**

### CODE REVIEW

**Comment by tswhison** [comment]
The fpgainfo unit tests are failing with this change.  Please have a look.

fpgainfo_c/fpgainfo_c_p.get_metrics0/0, where GetParam() = "skx-p"
fpgainfo_c/fpgainfo_c_p.get_metrics1/0, where GetParam() = "skx-p"
fpgainfo_c/fpgainfo_c_p.get_metrics2/0, where GetParam() = "skx-p"

**Comment by anandaravuri** [comment]
> The fpgainfo unit tests are failing with this change. Please have a look.
> 
> fpgainfo_c/fpgainfo_c_p.get_metrics0/0, where GetParam() = "skx-p"
> fpgainfo_c/fpgainfo_c_p.get_metrics1/0, where GetParam() = "skx-p"
> fpgainfo_c/fpgainfo_c_p.get_metrics2/0, where GetParam() = "skx-p"

will remove skx-p in another merge request.

**Comment by tswhison** [comment]
> > The fpgainfo unit tests are failing with this change. Please have a look.
> > fpgainfo_c/fpgainfo_c_p.get_metrics0/0, where GetParam() = "skx-p"
> > fpgainfo_c/fpgainfo_c_p.get_metrics1/0, where GetParam() = "skx-p"
> > fpgainfo_c/fpgainfo_c_p.get_metrics2/0, where GetParam() = "skx-p"
> 
> will remove skx-p in another merge request.

Let's go ahead and get it fixed here, otherwise CI will be broken once this goes in.

**Comment by anandaravuri** [comment]
> > > The fpgainfo unit tests are failing with this change. Please have a look.
> > > fpgainfo_c/fpgainfo_c_p.get_metrics0/0, where GetParam() = "skx-p"
> > > fpgainfo_c/fpgainfo_c_p.get_metrics1/0, where GetParam() = "skx-p"
> > > fpgainfo_c/fpgainfo_c_p.get_metrics2/0, where GetParam() = "skx-p"
> > 
> > 
> > will remove skx-p in another merge request.
> 
> Let's go ahead and get it fixed here, otherwise CI will be broken once this goes in.



> > > The fpgainfo unit tests are failing with this change. Please have a look.
> > > fpgainfo_c/fpgainfo_c_p.get_metrics0/0, where GetParam() = "skx-p"
> > > fpgainfo_c/fpgainfo_c_p.get_metrics1/0, where GetParam() = "skx-p"
> > > fpgainfo_c/fpgainfo_c_p.get_metrics2/0, where GetParam() = "skx-p"
> > 
> > 
> > will remove skx-p in another merge request.
> 
> Let's go ahead and get it fixed here, otherwise CI will be broken once this goes in.

[Ananda]  DFL driver metrics API changes will fail fpgainfo test cases.  will remove SKX-P in another Merge request.

**Pull request merged**
