### PR TITLE
Implement fpgaWriteMMIO512 for VFIO

### PR DESCRIPTION
**Pull request by michael-adler**

### CODE REVIEW

**Comment by michael-adler** [comment]
Tested on HW with a Rel1 build

**Review by r-rojo — COMMENTED** [review]
Should the macro be `OPAE_FLAG_HAS_AVX512`?

**Comment by michael-adler** [comment]
HAS_AVX512 makes more sense. I just copied the code from xfpga.

**Comment by michael-adler** [comment]
@r-rojo Done: changed to AVX512

**Review by r-rojo — APPROVED** [review]

**Pull request merged**
