### PR TITLE
libopae-v.so: filter for supported devices

### PR DESCRIPTION
**Pull request by tswhison**
Previously, the plugin was globbing in /sys/bus/drivers/vfio-pci
and creating a pci_device for each device currently bound to the
vfio-pci driver. This implementation errantly returned tokens for
the E810-C backplane device when DPDK workloads were active.

The change introduces a supported_devices table and one additional
check of the current device's vendor/device ID before creating a
pci_device for the glob result in question.

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

### CODE REVIEW

**Review by r-rojo — COMMENTED** [review]
Sorry I missed this earlier but we could probably simply this check around like 264. We could probably use a stack structure and only allocate/copy to a pointer if the check passes.

**Review by r-rojo — APPROVED** [review]
🏃

**Review by ajgrier — COMMENTED** [review]
we have got to do a better job at this than hard-coding PCI IDs into tables. maybe a newer revision generates a table by parsing config files?

**Comment by tswhison** [comment]
> we have got to do a better job at this than hard-coding PCI IDs into tables. maybe a newer revision generates a table by parsing config files?

Yes, that was the plan until I got tapped to write the OPAE HAS.  It's still on the list somewhere, just not sure where at this point.

**Pull request merged**
