### PR TITLE
libopae-c: build libopae-c-ase only when ase is enabled

### PR DESCRIPTION
**Pull request by hundeboll-silicom**
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>

### CODE REVIEW

**Review by tswhison — APPROVED** [review]

**Review by tswhison — COMMENTED** [review]
If we merge this change, with the addition of libopae-c-ase.so to the RPMs [1821](https://github.com/OPAE/opae-sdk/pull/1821/files), we will need to update all the docs and CI to include -DBUILD_ASE=yes.

**Comment by hundeboll-silicom** [comment]
> If we merge this change, with the addition of libopae-c-ase.so to the RPMs [1821](https://github.com/OPAE/opae-sdk/pull/1821/files), we will need to update all the docs and CI to include -DBUILD_ASE=yes, when building RPMs.

Are you sure?

The `opae.spec.in` already guards the `opae-ase` package with `%if %with_ase == "ON"`[1], and https://github.com/OPAE/opae-sdk/pull/1821 adds the library to the `opae-ase` package.

[1] https://github.com/OPAE/opae-sdk/blob/master/opae.spec.in#L268

**Comment by tswhison** [comment]
> Are you sure?> > If we merge this change, with the addition of libopae-c-ase.so to the RPMs [1821](https://github.com/OPAE/opae-sdk/pull/1821/files), we will need to update all the docs and CI to include -DBUILD_ASE=yes, when building RPMs.
> 
> 
> The `opae.spec.in` already guards the `opae-ase` package with `%if %with_ase == "ON"`[1], and [OPAE/opae-sdk#1821](https://github.com/OPAE/opae-sdk/pull/1821) adds the library to the `opae-ase` package.
> 
> [1] https://github.com/OPAE/opae-sdk/blob/master/opae.spec.in#L268

Ah yes, you are correct.  However, per opae-libs/CMakeLists.txt we should change the FLAG being used from BUILD_ASE to OPAE_BUILD_SIM and deprecate all uses of BUILD_ASE.  Does this seem like a good place to make that change?

**Comment by hundeboll-silicom** [comment]
> Does this seem like a good place to make that change?

We are not using ASE and I haven't worked with it, so I would rather not mess too much with it.

**Comment by tswhison** [comment]
I think we can safely change the use of @BUILD_ASE@ in opae.spec.in to @OPAE_BUILD_SIM@.  The rest of the instances (looks like 1 in samples/CMakeLists.txt) can be done elsewhere.  Thanks!

**Comment by southerngs** [comment]
Why are we switching from `OPAE_BUILD_SIM` to `BUILD_ASE`? Are both flags required now?  The user guide gives example using `OPAE_BUILD_SIM`

https://github.com/OPAE/opae-sdk/blob/master/doc/src/ase_userguide/ase_userguide.md

`cmake ../ -DOPAE_BUILD_SIM=YES -DCMAKE_INSTALL_PREFIX=/tmp/opae/myinst/`

It looks like this is broken now.  At least the scripts that I use for ASE with OpenCL stopped working until I also added `BUILD_ASE`.  We may have other users that have scripts using ASE that may be surprised by this change.

**Pull request merged**
